## 2026 Midterm Exam - Computing Portion - Part 1 - Data Analysis in Jupyter with Pandas
### Solutions
See word doc for instructions.

In [1]:
import pandas as pd
df = pd.read_csv('fifa-under19-2019.csv')

a)	Display the first five rows of df.

In [2]:
df.head()

,Unnamed: 0,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,...,Work Rate,Body Type,Real Face,Position,Jersey Number,Joined,Loaned From,Contract Valid Until,Height,Weight
0,226,235243,M. de Ligt,18,Netherlands,82,91,Ajax,€27M,€11K,...,Medium/ Medium,Normal,Yes,RCB,3.0,24-Oct-16,NaN,2021,6'2,196lbs
1,1004,233049,J. Sancho,18,England,77,89,Borussia Dortmund,€14.5M,€22K,...,Medium/ Medium,Lean,No,RM,7.0,31-Aug-17,NaN,2022,5'11,168lbs
2,1143,238794,Vinícius Júnior,17,Brazil,77,92,Real Madrid,€17.5M,€66K,...,High/ Medium,Lean,No,LW,28.0,12-Jul-18,NaN,2025,5'9,161lbs
3,1800,235883,R. Sessegnon,18,England,75,88,Fulham,€12M,€27K,...,High/ Medium,Lean,Yes,LM,3.0,9-Aug-16,NaN,2020,5'10,154lbs
4,2640,241168,G. Chakvetadze,18,Georgia,73,86,KAA Gent,€7M,€10K,...,Medium/ Medium,Lean,No,LM,7.0,30-Aug-17,NaN,2020,5'10,165lbs

b) Find the name, nationality, club, height, and weight of the player with the maximum value for "Potential".

In [3]:
df[df['Potential'] == df['Potential'].max()][['Name','Nationality','Club','Height','Weight']]

              Name Nationality         Club Height  Weight
2  Vinícius Júnior      Brazil  Real Madrid    5'9  161lbs

c) Create a new column called "Mix" that is the average of the two columns "Weak Foot" and "Skill Moves". Display your data frame so that this new column is visible.

In [4]:
df['Mix'] = (df['Weak Foot'] + df['Skill Moves']) / 2
df.head()

,Unnamed: 0,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,...,Body Type,Real Face,Position,Jersey Number,Joined,Loaned From,Contract Valid Until,Height,Weight,Mix
0,226,235243,M. de Ligt,18,Netherlands,82,91,Ajax,€27M,€11K,...,Normal,Yes,RCB,3.0,24-Oct-16,NaN,2021,6'2,196lbs,3.0
1,1004,233049,J. Sancho,18,England,77,89,Borussia Dortmund,€14.5M,€22K,...,Lean,No,RM,7.0,31-Aug-17,NaN,2022,5'11,168lbs,4.0
2,1143,238794,Vinícius Júnior,17,Brazil,77,92,Real Madrid,€17.5M,€66K,...,Lean,No,LW,28.0,12-Jul-18,NaN,2025,5'9,161lbs,4.5
3,1800,235883,R. Sessegnon,18,England,75,88,Fulham,€12M,€27K,...,Lean,Yes,LM,3.0,9-Aug-16,NaN,2020,5'10,154lbs,3.5
4,2640,241168,G. Chakvetadze,18,Georgia,73,86,KAA Gent,€7M,€10K,...,Lean,No,LM,7.0,30-Aug-17,NaN,2020,5'10,165lbs,3.0

d)	The “Overall” field provides a player’s current ability rating where higher numbers are better. “Position” indicates where a player plays on the field, e.g. LM means left midfielder. Find the average (mean) value of “Overall” for each “Position” and report these in descending order of “Overall” value. Hint: use groupby.

In [5]:
by_club = df.groupby('Position')
by_club['Overall'].mean().sort_values(ascending=False)

Position
LCB    68.750000
LF     67.000000
LDM    65.666667
RCB    65.166667
LCM    61.600000
LS     61.000000
RDM    60.000000
RCM    59.875000
LW     59.814815
RM     59.428571
LWB    58.750000
CAM    58.634146
LM     58.540000
RW     57.866667
CDM    57.785714
CF     57.363636
CB     57.300813
ST     57.035714
LB     56.932203
RB     56.595745
RWB    56.333333
CM     55.934524
GK     54.589744
RS     53.500000
Name: Overall, dtype: float64